# Generated by Django 5.1.6 on 2025-02-10 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=168)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('race', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=10)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('birth_date', models.DateTimeField()),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='api_app.city')),
            ],
        ),
    ]
